pipeline {
    
    agent {
        docker {
            image 'python:2.7.16-slim'
            args '--user root'
        }
    }
    
    stages {
        stage('build') {
        	when {
        	    changeset "**/vote/**"
        	}
        	
            steps {
                echo 'Compiling vote app'
                dir('vote') {
                    sh 'pip install -r requirements.txt' 
                }
            }
        }
        
        stage('test') {
        	when {
        	    changeset "**/vote/**"
        	}
        	
            steps {
                echo 'Running Unit Tests on vote App'
                dir('vote') {
                    sh 'nosetests -v'   
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline for vote is complete...'
        }
        failure {
            slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success {
			slackSend (channel: "instavote-cd", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}