version: "3.7"

volumes:
        db-data:

networks:
        instavote:
                driver: bridge

services:
  redis:
          image: redis:alpine
          networks:
                  - instavote

  db:
          image: postgres:9.4
          volumes:
                  - "db-data:/var/lib/postgresql/data"
          environment:
                  - POSTGRES_HOST_AUTH_METHOD=trust
          env_file:
                  - .env
          ports:
                  - 5432:5432
          networks:
                  - instavote

  vote:
          image: visdan/vote:master
          ports:
                  - 5000:80
          depends_on:
                  - redis
          networks:
                  - instavote

  result:
          image: visdan/result:master
          ports:
                  - 5001:80
          depends_on:
                  - db
          networks:
                  - instavote


  worker:
          image: visdan/worker:master
          depends_on:
                  - redis
                  - db
          networks:
                  - instavote