pipeline {
    
    agent {
        docker {
            image 'maven:3.6.1-jdk8-alpine'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
    
    stages {
        stage('build') {
        	when {
        	    changeset "**/worker/**"
        	}
        	
            steps {
                echo 'Compiling worker app'
                dir('worker') {
                    sh 'mvn compile'   
                }
            }
        }
        
        stage('test') {
        	when {
        	    changeset "**/worker/**"
        	}
        	
            steps {
                echo 'Running Unit Tests on worker App'
                dir('worker') {
                    sh 'mvn clean test'   
                }
            }
        }
        
        stage('package') {
        	when {
        	    branch 'master'
        	    changeset "**/worker/**"
        	}

            steps {
                echo 'Packaging worker app'
                dir('worker') {
                    sh 'mvn package -DskipTests'  
					archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true 
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline for worker is complete...'
        }
        failure {
            slackSend (channel: "instavote-cd", message: "Build Failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
        success {
			slackSend (channel: "instavote-cd", message: "Build Succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
        }
    }
}